/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Client = IDL.Record({
  'id' : IDL.Text,
  'paymentCycle' : IDL.Text,
  'status' : IDL.Text,
  'feeAmount' : IDL.Nat,
  'assignedReformer' : IDL.Text,
  'name' : IDL.Text,
  'planStartDate' : IDL.Int,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'sessionFrequency' : IDL.Nat,
});
export const Session = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Nat,
  'sessionType' : IDL.Text,
  'enrolled' : IDL.Nat,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'trainer' : IDL.Text,
  'reformerAssignment' : IDL.Text,
  'capacity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createClient' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Int,
      ],
      [],
      [],
    ),
  'createSession' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'deleteClient' : IDL.Func([IDL.Text], [], []),
  'deleteSession' : IDL.Func([IDL.Text], [], []),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllReformers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getClient' : IDL.Func([IDL.Text], [Client], ['query']),
  'getReformerStatus' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getSession' : IDL.Func([IDL.Text], [Session], ['query']),
  'updateClient' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Int,
      ],
      [],
      [],
    ),
  'updateReformerStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateSession' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Client = IDL.Record({
    'id' : IDL.Text,
    'paymentCycle' : IDL.Text,
    'status' : IDL.Text,
    'feeAmount' : IDL.Nat,
    'assignedReformer' : IDL.Text,
    'name' : IDL.Text,
    'planStartDate' : IDL.Int,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'sessionFrequency' : IDL.Nat,
  });
  const Session = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Nat,
    'sessionType' : IDL.Text,
    'enrolled' : IDL.Nat,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'trainer' : IDL.Text,
    'reformerAssignment' : IDL.Text,
    'capacity' : IDL.Nat,
  });
  
  return IDL.Service({
    'createClient' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Int,
        ],
        [],
        [],
      ),
    'createSession' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'deleteClient' : IDL.Func([IDL.Text], [], []),
    'deleteSession' : IDL.Func([IDL.Text], [], []),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllReformers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getClient' : IDL.Func([IDL.Text], [Client], ['query']),
    'getReformerStatus' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getSession' : IDL.Func([IDL.Text], [Session], ['query']),
    'updateClient' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Int,
        ],
        [],
        [],
      ),
    'updateReformerStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateSession' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };