/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : string,
  'paymentCycle' : string,
  'status' : string,
  'feeAmount' : bigint,
  'assignedReformer' : string,
  'name' : string,
  'planStartDate' : bigint,
  'email' : string,
  'phone' : string,
  'sessionFrequency' : bigint,
}
export interface Session {
  'id' : string,
  'duration' : bigint,
  'sessionType' : string,
  'enrolled' : bigint,
  'date' : bigint,
  'name' : string,
  'time' : string,
  'trainer' : string,
  'reformerAssignment' : string,
  'capacity' : bigint,
}
export interface _SERVICE {
  'createClient' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      string,
      bigint,
      string,
      string,
      bigint,
    ],
    undefined
  >,
  'createSession' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      bigint,
      string,
      string,
      string,
      bigint,
      bigint,
    ],
    undefined
  >,
  'deleteClient' : ActorMethod<[string], undefined>,
  'deleteSession' : ActorMethod<[string], undefined>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllReformers' : ActorMethod<[], Array<[string, string]>>,
  'getAllSessions' : ActorMethod<[], Array<Session>>,
  'getClient' : ActorMethod<[string], Client>,
  'getReformerStatus' : ActorMethod<[string], string>,
  'getSession' : ActorMethod<[string], Session>,
  'updateClient' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      string,
      bigint,
      string,
      string,
      bigint,
    ],
    undefined
  >,
  'updateReformerStatus' : ActorMethod<[string, string], undefined>,
  'updateSession' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      bigint,
      string,
      string,
      string,
      bigint,
      bigint,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];